options(repos = c(CRAN = "https://cloud.r-project.org"))
install.packages("sf")
install.packages("plotly")
install.packages("leaflet")
install.packages("tidyverse")
install.packages("dataRetrieval")
install.packages("rnaturalearth")
install.packages("devtools")
install.packages("tools")
install.packages("IRkernel")
devtools::install_github("ropensci/rnaturalearthhires")
